services:
  bomberman-server:
    image: local/bomberman/server:devel
    build:
      dockerfile: dev.Dockerfile
      context: ./server
    restart: never
    ports:
      - 8080:8080
    volumes:
      - ../src:/app

  go-client:
    image: local/bomberman/go-client:devel
    build:
      dockerfile: dev.Dockerfile
      context: ./go_client
    restart: never
    volumes:
      - ../src:/app
