services:
  bomberman-server:
    image: local/bomberman/server:devel
    container_name: bomberman-sever
    build:
      dockerfile: dev.Dockerfile
      context: ../
    restart: never
    networks:
      - bomb-net
    ports:
      - 8038:8038
    volumes:
      - ../src:/app

networks:
  bomb-net: {}
