// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.977
package home

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func footer() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<footer class=\"footer footer-center p-10 py-15 bg-base-300 text-base-content mt-10\"><div class=\"container mx-auto px-4\"><div><img width=\"35px\" src=\"/static/images/BombAheadLogoSmall.png\" alt=\"BombAhead Logo\"></div><div><p class=\"font-bold\">BombAhead Project by N3moAhead.</p><p>This is a passion project. I don't want your data. The only information stored is your GitHub user ID, username, and avatar URL, which is necessary for simple authentication. No tracking, no analytics, just Bomberman.</p></div><div><div class=\"grid grid-flow-col gap-4\"><a href=\"https://github.com/N3moAhead\" class=\"link link-hover\" target=\"_blank\" rel=\"noopener noreferrer\"><img width=\"50px\" src=\"/static/images/GitHub_Invertocat_Black.svg\" alt=\"Github Icon\"></a></div></div></div></footer>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
