services:
  bomberman-go-client:
    image: local/bomberman/go-client:devel
    container_name: go_client
    build:
      dockerfile: dev.Dockerfile
      context: ../
    restart: never
    volumes:
      - ../src:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
