services:
  go-client:
    image: local/bomberman/go-client:devel
    container_name: go_client
    build:
      dockerfile: dev.Dockerfile
      context: ../
    restart: never
    networks:
      - bomb-net
    volumes:
      - ../src:/app

networks:
  bomb-net:
    external:
      name: local_bomb_network
