FROM docker.io/golang:1.25-alpine AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download && go mod verify

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o /matchmaker ./cmd/matchmaker/main.go

FROM docker.io/alpine:latest

WORKDIR /app

COPY --from=builder /matchmaker .

CMD [ "./matchmaker" ]
